name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec remix vite:dev"

[[extensions]]
type = "admin_link"
title = "Dashboard"
url = "/dashboard"

[[extensions]]
type = "admin_link"
title = "Bookings"
url = "/bookings"
